chore(deps): update pepr (#1197)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence | Type |
Update |
|---|---|---|---|---|---|---|---|
| [lint-staged](https://redirect.github.com/lint-staged/lint-staged) |
[`15.3.0` ->
`15.4.3`](https://renovatebot.com/diffs/npm/lint-staged/15.3.0/15.4.3) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/lint-staged/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/lint-staged/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/lint-staged/15.3.0/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/lint-staged/15.3.0/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| devDependencies | minor |
| [pepr](https://redirect.github.com/defenseunicorns/pepr) | [`0.42.3`
-> `0.44.0`](https://renovatebot.com/diffs/npm/pepr/0.42.3/0.44.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/pepr/0.44.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/pepr/0.44.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/pepr/0.42.3/0.44.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/pepr/0.42.3/0.44.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| dependencies | minor |
|
[registry1.dso.mil/ironbank/opensource/defenseunicorns/pepr/controller](https://redirect.github.com/defenseunicorns/pepr)
([source](https://repo1.dso.mil/dsop/opensource/defenseunicorns/pepr/controller))
| `v0.42.3` -> `v0.44.0` |
[![age](https://developer.mend.io/api/mc/badges/age/docker/registry1.dso.mil%2fironbank%2fopensource%2fdefenseunicorns%2fpepr%2fcontroller/v0.44.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/docker/registry1.dso.mil%2fironbank%2fopensource%2fdefenseunicorns%2fpepr%2fcontroller/v0.44.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/docker/registry1.dso.mil%2fironbank%2fopensource%2fdefenseunicorns%2fpepr%2fcontroller/v0.42.3/v0.44.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/docker/registry1.dso.mil%2fironbank%2fopensource%2fdefenseunicorns%2fpepr%2fcontroller/v0.42.3/v0.44.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
| | minor |

---

### Release Notes

<details>
<summary>lint-staged/lint-staged (lint-staged)</summary>

###
[`v15.4.3`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1543)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.2...v15.4.3)

##### Patch Changes

-
[#&#8203;1512](https://redirect.github.com/lint-staged/lint-staged/pull/1512)
[`cbfed1d`](https://redirect.github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1)
Thanks [@&#8203;tarik02](https://redirect.github.com/tarik02)! - Adjust
TypeScript types for the default export so that it can be used as a
value without error TS2693.

###
[`v15.4.2`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1542)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.1...v15.4.2)

##### Patch Changes

-
[#&#8203;1509](https://redirect.github.com/lint-staged/lint-staged/pull/1509)
[`8827ebf`](https://redirect.github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Change
*lint-staged*'s dependencies to use [caret (`^`)
ranges](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004)
instead of [tilde
(`~`)](https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1).
This makes it easier for package managers to perform dependency
management when minor-level updates are also permitted instead of just
patch-level.

###
[`v15.4.1`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1541)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.0...v15.4.1)

##### Patch Changes

-
[#&#8203;1504](https://redirect.github.com/lint-staged/lint-staged/pull/1504)
[`1c7a45e`](https://redirect.github.com/lint-staged/lint-staged/commit/1c7a45ed2c7fee9d5f55337be16a51e4c9b240e1)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Default
TypeScript config filenames match JS equivalents.

-
[#&#8203;1504](https://redirect.github.com/lint-staged/lint-staged/pull/1504)
[`9cc18c9`](https://redirect.github.com/lint-staged/lint-staged/commit/9cc18c9debb185490f9ae4f9c1d21ec8c2587393)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Add missing
conditional exports syntax for TypeScript types.

###
[`v15.4.0`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1540)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.3.0...v15.4.0)

##### Minor Changes

-
[#&#8203;1500](https://redirect.github.com/lint-staged/lint-staged/pull/1500)
[`a8ec1dd`](https://redirect.github.com/lint-staged/lint-staged/commit/a8ec1ddb587d2c1c2420dbb4baff8160f0ac46c9)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! -
*Lint-staged* now provides TypeScript types for the configuration and
main Node.js API. You can use the JSDoc syntax in your JS configuration
files:

    ```js
    /**
     * @&#8203;filename: lint-staged.config.js
     * @&#8203;type {import('lint-staged').Configuration}
     */
    export default {
      '*': 'prettier --write',
    }
    ```

It's also possible to use the `.ts` file extension for the configuration
if your Node.js version supports it. The `--experimental-strip-types`
flag was introduced in [Node.js
v22.6.0](https://redirect.github.com/nodejs/node/releases/tag/v22.6.0)
and unflagged in
[v23.6.0](https://redirect.github.com/nodejs/node/releases/tag/v23.6.0),
enabling Node.js to execute TypeScript files without additional
configuration.

    ```shell
    export NODE_OPTIONS="--experimental-strip-types"

    npx lint-staged --config lint-staged.config.ts
    ```

##### Patch Changes

-
[#&#8203;1501](https://redirect.github.com/lint-staged/lint-staged/pull/1501)
[`9b79364`](https://redirect.github.com/lint-staged/lint-staged/commit/9b793640e1f87b46e4f40fcfc1ecf9d6f6013ac9)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Handle
possible failures when logging user shell for debug info.

</details>

<details>
<summary>defenseunicorns/pepr (pepr)</summary>

###
[`v0.44.0`](https://redirect.github.com/defenseunicorns/pepr/releases/tag/v0.44.0)

[Compare
Source](https://redirect.github.com/defenseunicorns/pepr/compare/v0.43.0...v0.44.0)

#### What's Changed

- feat: webhook analytics timeouts by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1717](https://redirect.github.com/defenseunicorns/pepr/pull/1717)
- fix: local integration testing setup/timeouts by
[@&#8203;samayer12](https://redirect.github.com/samayer12) in
[https://github.com/defenseunicorns/pepr/pull/1705](https://redirect.github.com/defenseunicorns/pepr/pull/1705)
- chore: remove soak-interrupts.yaml by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1714](https://redirect.github.com/defenseunicorns/pepr/pull/1714)
- chore: docs refresher by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1683](https://redirect.github.com/defenseunicorns/pepr/pull/1683)
- chore: backwards compat - open to team ideas! by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1707](https://redirect.github.com/defenseunicorns/pepr/pull/1707)
- chore: bump undici from 7.2.3 to 7.3.0 in the development-dependencies
group by [@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1710](https://redirect.github.com/defenseunicorns/pepr/pull/1710)
- chore: bump github/codeql-action from 3.28.2 to 3.28.3 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1711](https://redirect.github.com/defenseunicorns/pepr/pull/1711)
- chore: bump codecov/codecov-action from 5.1.2 to 5.2.0 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1712](https://redirect.github.com/defenseunicorns/pepr/pull/1712)
- chore: bump anchore/sbom-action from 0.17.9 to 0.18.0 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1720](https://redirect.github.com/defenseunicorns/pepr/pull/1720)
- chore: bump codecov/codecov-action from 5.2.0 to 5.3.0 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1721](https://redirect.github.com/defenseunicorns/pepr/pull/1721)
- chore: bump github/codeql-action from 3.28.3 to 3.28.4 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1722](https://redirect.github.com/defenseunicorns/pepr/pull/1722)
- chore: bump
[@&#8203;types/node](https://redirect.github.com/types/node) from
22.10.7 to 22.10.10 in the development-dependencies group by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1718](https://redirect.github.com/defenseunicorns/pepr/pull/1718)
- chore: bump anchore/scan-action from 6.0.0 to 6.1.0 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1719](https://redirect.github.com/defenseunicorns/pepr/pull/1719)

**Full Changelog**:
https://github.com/defenseunicorns/pepr/compare/v0.43.0...v0.44.0

###
[`v0.43.0`](https://redirect.github.com/defenseunicorns/pepr/releases/tag/v0.43.0)

[Compare
Source](https://redirect.github.com/defenseunicorns/pepr/compare/v0.42.3...v0.43.0)

#### Features 🤓

- feat: additionalIgnoredNamespaces at runtime through helm by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1641](https://redirect.github.com/defenseunicorns/pepr/pull/1641)

*Allows additional ignored namespaces to be set in the helm chart in
addition to the namespaces set in
[`pepr`](https://docs.pepr.dev/main/user-guide/customization/#packagejson-configurations-table)
section of `package.json`.*

#### Watch Out 🚧

- chore: chainguard node23 is a no, so... distroless? by
[@&#8203;btlghrants](https://redirect.github.com/btlghrants) in
[https://github.com/defenseunicorns/pepr/pull/1684](https://redirect.github.com/defenseunicorns/pepr/pull/1684)

**Rebuild required (`npx pepr build`)** - The distroless image has a
smaller footprint with less CVEs, however, it does not have *node* in
the same path on the container. Therefore, we needed to switch the
`commands` on the deployments for `args`. Make sure you do a rebuild and
this will be done for you.

**Note**- We always recommend rebuilding when you bring in new versions.

#### What's Changed ♻️

- chore: give best practices around mutations by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1672](https://redirect.github.com/defenseunicorns/pepr/pull/1672)

- chore: add return types to build.ts by
[@&#8203;tamirazrab](https://redirect.github.com/tamirazrab) in
[https://github.com/defenseunicorns/pepr/pull/1687](https://redirect.github.com/defenseunicorns/pepr/pull/1687)

- chore: update soak-interrupts test by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1702](https://redirect.github.com/defenseunicorns/pepr/pull/1702)

- chore: add return types to loader.ts by
[@&#8203;samayer12](https://redirect.github.com/samayer12) in
[https://github.com/defenseunicorns/pepr/pull/1648](https://redirect.github.com/defenseunicorns/pepr/pull/1648)

- chore: remove unused property in assets class by
[@&#8203;samayer12](https://redirect.github.com/samayer12) in
[https://github.com/defenseunicorns/pepr/pull/1647](https://redirect.github.com/defenseunicorns/pepr/pull/1647)

- chore: encourage return types in function definitions by
[@&#8203;samayer12](https://redirect.github.com/samayer12) in
[https://github.com/defenseunicorns/pepr/pull/1364](https://redirect.github.com/defenseunicorns/pepr/pull/1364)

- fix(CI): grant write permission to CI job by
[@&#8203;samayer12](https://redirect.github.com/samayer12) in
[https://github.com/defenseunicorns/pepr/pull/1658](https://redirect.github.com/defenseunicorns/pepr/pull/1658)

- chore: remove unused mocking by
[@&#8203;samayer12](https://redirect.github.com/samayer12) in
[https://github.com/defenseunicorns/pepr/pull/1664](https://redirect.github.com/defenseunicorns/pepr/pull/1664)

- chore: remove circular dependencies in `src/lib/assets/` by
[@&#8203;samayer12](https://redirect.github.com/samayer12) in
[https://github.com/defenseunicorns/pepr/pull/1652](https://redirect.github.com/defenseunicorns/pepr/pull/1652)

- test: add cli test to validate multiple manifest generation paths
result in comparable output by
[@&#8203;btlghrants](https://redirect.github.com/btlghrants) in
[https://github.com/defenseunicorns/pepr/pull/1642](https://redirect.github.com/defenseunicorns/pepr/pull/1642)

- chore: remove max-statements warning in `schedule.test.ts` by
[@&#8203;samayer12](https://redirect.github.com/samayer12) in
[https://github.com/defenseunicorns/pepr/pull/1671](https://redirect.github.com/defenseunicorns/pepr/pull/1671)

- chore: pass imagePullSecret to helm by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1670](https://redirect.github.com/defenseunicorns/pepr/pull/1670)

- chore: remove write perms image digest workflow by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1677](https://redirect.github.com/defenseunicorns/pepr/pull/1677)

[https://github.com/defenseunicorns/pepr/pull/1680](https://redirect.github.com/defenseunicorns/pepr/pull/1680)1680

- chore: removing digestabot update workflow by
[@&#8203;btlghrants](https://redirect.github.com/btlghrants) in
[https://github.com/defenseunicorns/pepr/pull/1686](https://redirect.github.com/defenseunicorns/pepr/pull/1686)

- chore: watch_failure template for reporting watch failures by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1682](https://redirect.github.com/defenseunicorns/pepr/pull/1682)

- chore: deployments for soak for new image by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1689](https://redirect.github.com/defenseunicorns/pepr/pull/1689)

- chore: validate build arguments that are used together add docs by
[@&#8203;cmwylie19](https://redirect.github.com/cmwylie19) in
[https://github.com/defenseunicorns/pepr/pull/1678](https://redirect.github.com/defenseunicorns/pepr/pull/1678)

- chore: bump step-security/harden-runner from 2.10.3 to 2.10.4 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1690](https://redirect.github.com/defenseunicorns/pepr/pull/1690)

- chore: bump kubernetes-fluent-client from 3.3.7 to 3.3.8 in the
production-dependencies group by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1685](https://redirect.github.com/defenseunicorns/pepr/pull/1685)

- chore: bump trufflesecurity/trufflehog from 3.88.1 to 3.88.2 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1646](https://redirect.github.com/defenseunicorns/pepr/pull/1646)

- chore: bump actions/upload-artifact from 4.5.0 to 4.6.0 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1645](https://redirect.github.com/defenseunicorns/pepr/pull/1645)

- chore: bump undici from 7.2.0 to 7.2.1 in the development-dependencies
group by [@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1643](https://redirect.github.com/defenseunicorns/pepr/pull/1643)

- chore: bump step-security/harden-runner from 2.10.2 to 2.10.3 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1644](https://redirect.github.com/defenseunicorns/pepr/pull/1644)

- chore: bump github/codeql-action from 3.28.0 to 3.28.1 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1650](https://redirect.github.com/defenseunicorns/pepr/pull/1650)

- chore: bump the development-dependencies group with 2 updates by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in

- chore: bump
[@&#8203;types/node](https://redirect.github.com/types/node) from
22.10.5 to 22.10.6 in the development-dependencies group by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1653](https://redirect.github.com/defenseunicorns/pepr/pull/1653)

- chore: bump undici from 7.2.1 to 7.2.2 in the development-dependencies
group by [@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1673](https://redirect.github.com/defenseunicorns/pepr/pull/1673)

- chore: bump github/codeql-action from 3.28.1 to 3.28.2 by
[@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1703](https://redirect.github.com/defenseunicorns/pepr/pull/1703)

- chore: bump distroless/nodejs22-debian12 from `06298f8` to `5e248b9`
by [@&#8203;dependabot](https://redirect.github.com/dependabot) in
[https://github.com/defenseunicorns/pepr/pull/1704](https://redirect.github.com/defenseunicorns/pepr/pull/1704)

**Full Changelog**:
https://github.com/defenseunicorns/pepr/compare/v0.42.3...v0.43.0

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/defenseunicorns/uds-core).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xMDcuMCIsInVwZGF0ZWRJblZlciI6IjM5LjEyNS4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Chance <139784371+UnicornChance@users.noreply.github.com>
Co-authored-by: Noah <40781376+noahpb@users.noreply.github.com>